docker: fix 'osrd-compose host dev-front sw'
Remove (broken) silent force of host file and explicitly output error
when 'host' is missing.

Signed-off-by: Pierre-Etienne Bougué <bougue.pe@proton.me>

diff --git a/osrd-compose b/osrd-compose
--- a/osrd-compose
+++ b/osrd-compose
@@ -97,6 +97,12 @@ has_flag() {
     return 1
 }
 
+# TODO: currently "single-worker" only works with "host", allowing no-host would be nice
+if has_flag "sw" && ! has_flag "host"; then
+    echo "Error: 'sw' flag currently only works combined with 'host' flag"
+    exit 1
+fi
+
 if has_flag "host"; then
     compose_files+=("$OVERRIDE_DIR/docker-compose.host.yml")
 fi
@@ -111,9 +117,6 @@ fi
 
 if has_flag "sw"; then
     compose_files+=("$OVERRIDE_DIR/docker-compose.single-worker.yml")
-
-    # TODO: currently "single-worker" only works with "host", allowing no-host would be nice
-    compose_files+=("$OVERRIDE_DIR/docker-compose.host.yml")
 fi
 
 # Check if DOCKER_SOCKET is already set
